### ISSUE TITLE
Request: Host the jar file on github

### ISSUE THREAD

**Issue by hrj** [cybersearch2/cybersearch2-desugar#1]
On Github, you can make [a release](https://help.github.com/articles/about-releases/) for this project and add the `.jar` file as an artifact.

Also, another minor request..

The choice of `.andmore` directory name is a bit unusual. The toplevel directory (`.android`) is already hidden because of the leading `.`. The next level directories usually don't have a leading period. So the desugar directory can be located at `~/.android/andmore/desguar` instead of `~/.android/.andmore/desugar`

**Comment by cybersearch2** [comment]
The [desugar release](https://github.com/cybersearch2/cybersearch2-desugar/releases/tag/andmore-0.12.0) is done. The version number comes from the name of the originating branch. I have also acted on your very sensible request and edited the sources to remove the leading dot from the Andmore home location.
I am now starting work on the Andworx release.
